// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.11.2
// source: custom_errors.proto

package __

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// API: ResolveError
// Operation:  RESOLVE_ERROR_REQUEST 0x18B1805B
// ResultType: RESOLVE_ERROR_RESULT  0xEC02BAC4
// ------------------------------------------------------------------------------
type ResolveErrorRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Document *Document `protobuf:"bytes,1,opt,name=document,proto3" json:"document,omitempty"`
}

func (x *ResolveErrorRequest) Reset() {
	*x = ResolveErrorRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_custom_errors_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResolveErrorRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolveErrorRequest) ProtoMessage() {}

func (x *ResolveErrorRequest) ProtoReflect() protoreflect.Message {
	mi := &file_custom_errors_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolveErrorRequest.ProtoReflect.Descriptor instead.
func (*ResolveErrorRequest) Descriptor() ([]byte, []int) {
	return file_custom_errors_proto_rawDescGZIP(), []int{0}
}

func (x *ResolveErrorRequest) GetDocument() *Document {
	if x != nil {
		return x.Document
	}
	return nil
}

type ResolveErrorResult struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ResolveErrorResult) Reset() {
	*x = ResolveErrorResult{}
	if protoimpl.UnsafeEnabled {
		mi := &file_custom_errors_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResolveErrorResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolveErrorResult) ProtoMessage() {}

func (x *ResolveErrorResult) ProtoReflect() protoreflect.Message {
	mi := &file_custom_errors_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolveErrorResult.ProtoReflect.Descriptor instead.
func (*ResolveErrorResult) Descriptor() ([]byte, []int) {
	return file_custom_errors_proto_rawDescGZIP(), []int{1}
}

var File_custom_errors_proto protoreflect.FileDescriptor

var file_custom_errors_proto_rawDesc = []byte{
	0x0a, 0x13, 0x63, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x5f, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x73, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x1a,
	0x0d, 0x6f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x45,
	0x0a, 0x13, 0x52, 0x65, 0x73, 0x6f, 0x6c, 0x76, 0x65, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x2e, 0x0a, 0x08, 0x64, 0x6f, 0x63, 0x75, 0x6d, 0x65, 0x6e,
	0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62,
	0x75, 0x66, 0x2e, 0x44, 0x6f, 0x63, 0x75, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x08, 0x64, 0x6f, 0x63,
	0x75, 0x6d, 0x65, 0x6e, 0x74, 0x22, 0x14, 0x0a, 0x12, 0x52, 0x65, 0x73, 0x6f, 0x6c, 0x76, 0x65,
	0x45, 0x72, 0x72, 0x6f, 0x72, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x42, 0x04, 0x5a, 0x02, 0x2e,
	0x2f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_custom_errors_proto_rawDescOnce sync.Once
	file_custom_errors_proto_rawDescData = file_custom_errors_proto_rawDesc
)

func file_custom_errors_proto_rawDescGZIP() []byte {
	file_custom_errors_proto_rawDescOnce.Do(func() {
		file_custom_errors_proto_rawDescData = protoimpl.X.CompressGZIP(file_custom_errors_proto_rawDescData)
	})
	return file_custom_errors_proto_rawDescData
}

var file_custom_errors_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_custom_errors_proto_goTypes = []interface{}{
	(*ResolveErrorRequest)(nil), // 0: protobuf.ResolveErrorRequest
	(*ResolveErrorResult)(nil),  // 1: protobuf.ResolveErrorResult
	(*Document)(nil),            // 2: protobuf.Document
}
var file_custom_errors_proto_depIdxs = []int32{
	2, // 0: protobuf.ResolveErrorRequest.document:type_name -> protobuf.Document
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_custom_errors_proto_init() }
func file_custom_errors_proto_init() {
	if File_custom_errors_proto != nil {
		return
	}
	file_objects_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_custom_errors_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ResolveErrorRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_custom_errors_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ResolveErrorResult); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_custom_errors_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_custom_errors_proto_goTypes,
		DependencyIndexes: file_custom_errors_proto_depIdxs,
		MessageInfos:      file_custom_errors_proto_msgTypes,
	}.Build()
	File_custom_errors_proto = out.File
	file_custom_errors_proto_rawDesc = nil
	file_custom_errors_proto_goTypes = nil
	file_custom_errors_proto_depIdxs = nil
}
